### ISSUE TITLE
Too much padding in title

### ISSUE THREAD

**Issue by foderking** [deathau/Notation-for-Obsidian#8]
This plugin is great!. but I noticed there's a lot of padding at the top of the text in the title part of the file.
Is there a way to reduce it?

**Comment by foderking** [comment]
For reference
![Capture](https://user-images.githubusercontent.com/46138004/141729037-8b5e8957-5cba-4a82-992e-c3878052eea6.PNG)

**Comment by yarin-zhang** [comment]
You can add the following code snippet in `.obsidian\snippets` . It could solve article header shrinkage following title.

``` css
/* 解决文章页眉跟随标题收缩 */
.workspace-leaf-content[data-type=markdown] .view-header-title-container {
  width: 700px;
  margin-top: auto;
  height: auto;
  padding: 0;
  text-align: center;
}
```
